source 'https://rubygems.org'
gem 'gir_ffi-gtk', :require=>'gir_ffi-gtk3'
#gem 'ruby_js', :git => 'https://github.com/ppibburr/ruby_ffi-javascriptcore.git'
#gem 'ffi-webkit-js', :git => 'https://github.com/mvz/ffi-webkit-js.git'
gem 'eventmachine'
gem 'em-websocket'
gem 'multi_json'
gem 'json'
gem 'erubis'
gem 'ruby-wmctrl', :require=>'wmctrl'
gem 'pry'
gem 'pry-rescue'
